### PR TITLE
Remove NumPy <2 pin

### PR DESCRIPTION
**Pull request by seberg**
This PR removes the NumPy<2 pin.  `wholegraph` does not appear to be a heavy user of NumPy or CuPy, so it should be fine to simply remove the pin.
For other RAPIDS projects with heavier dependency, CuPy 13.3.0 was required (just released) to have sufficient good CuPy/NumPy interoperability.

### CODE REVIEW

**Comment by seberg** [comment]
This project has a very light NumPy and no CuPy dependency, so pinning was briefly useful for the transition when NumPy 2 came out, but unnecessary as soon as there were no obvious Python incompatibilities.
(The dependency is so light, there really should be no issue at all.)

**Comment by jakirkham** [comment]
Sebastian and I discussed the PyTorch question offline

<hr>

We observed a few things about PyTorch usage here:

1. PyTorch appears to be a dependency, but is not listed as one
2. Old versions of PyTorch are being installed in CI

These are documented in issue: https://github.com/rapidsai/wholegraph/issues/210

<hr>

This led to a separate question. PyTorch only started supporting NumPy 2 in PyTorch 2.3.0 ( https://github.com/pytorch/pytorch/issues/107302#issuecomment-2048405223 ). However the versions here are older than that. We observed.

1. Older PyTorch installed with NumPy 2 seems to be working here on CI
2. Testing an older PyTorch locally `import torch` works with NumPy 2
3. Testing tensor creation in PyTorch locally only issues a warning (no error)

<hr>

While it doesn't appear necessary to change PyTorch here, we still think it is a good idea to add the PyTorch dependency and update the versions used. However we don't know enough about how PyTorch is used here to develop a solution without more discussion. To facilitate discussion and reaching an acceptable solution, have raised issue: https://github.com/rapidsai/wholegraph/issues/210

**Comment by jakirkham** [comment]
[One job]( https://github.com/rapidsai/wholegraph/actions/runs/10531595361/job/29184558148?pr=208 ) had trouble finding the `libraft` package. While it doesn't explicitly show a network error, it is quit likely this happened. The other jobs in that group found `libraft` without issues

Restarted [that job]( https://github.com/rapidsai/wholegraph/actions/runs/10531595361/job/29188614887?pr=208 ) and it appears to have cleared up

So just noting this for posterity

**Review by jakirkham — APPROVED** [review]

**Comment by jakirkham** [comment]
Thanks Sebastian! 🙏

**Pull request merged**
