### PR TITLE
Revert "Add CUDA_STATIC_MATH_LIBRARIES"

### PR DESCRIPTION
**Pull request by KyleFromNVIDIA**
#190 was supposed to separate static CUDA math libraries from static CUDA runtime library, but accidentally pulled the runtime along with the math libraries. The way we'd normally fix this is by creating a separate variable for the runtime. However, since this project doesn't actually use any math libraries, we can just revert the whole thing.

Contributes to https://github.com/rapidsai/build-planning/issues/35

### CODE REVIEW

**Review by vyasr — APPROVED** [review]
I'm fine reverting since there's no use of math libs, but could you clarify what you mean by
> accidentally pulled the runtime along with the math libraries.

Was there some problem caused by #190, somewhere where we lost the runtime static linking altogether?

**Comment by KyleFromNVIDIA** [comment]
The problem caused by #190 was that the static linking of the runtime was suddenly controlled by `CUDA_STATIC_MATH_LIBRARIES` rather than `CUDA_STATIC_RUNTIME`. My intention at first was to have the runtime controlled by `CUDA_STATIC_RUNTIME` again, but when I reviewed the code and realized that nothing else was actually using `CUDA_STATIC_MATH_LIBRARIES`, I decided it would be best to just revert the entire change.

**Comment by vyasr** [comment]
I was looking at the call to `rapids_cuda_init_runtime` (which is using the right variable) and I didn't realize that the suffix was affecting the cudart library we link to. Got it, yes this is a necessary fix. Thanks.

**Pull request merged**
