### PR TITLE
Use RNG (random number generator) provided by RAFT

### PR DESCRIPTION
**Pull request by linhu-nv**
Replace the random number generator (RNG) implemented by wholegraph with RNG provided by RAFT. 
It is put forward by issue #7 and issue #23.

### CODE REVIEW

**Review by chuangz0 — COMMENTED** [review]
Looks good to me, thanks.

**Review by dongxuy04 — APPROVED** [review]
LGTM, thanks!

**Review by chuangz0 — APPROVED** [review]

**Pull request merged**
